import { BlockDefinition } from '../../../models/Block';

export const functionBlocks: BlockDefinition[] = [
  {
    id: 'func_define',
    category: 'functions', type: 'hat',
    label: 'function %1',
    inputs: [{ name: 'name', type: 'string', label: 'name', defaultValue: 'myFunction' }],
    canHaveNext: true, hasBranch: false, branchCount: 0,
    tooltip: 'Define a reusable function',
    luaGenerator: (block, ctx) => {
      const name = ctx.generateInput(block.inputValues.name, ctx);
      // The body is generated by the chain following this hat
      return `${ctx.getIndent()}local function ${name.replace(/"/g, '')}()`;
    },
  },
  {
    id: 'func_define_params',
    category: 'functions', type: 'hat',
    label: 'function %1 with %2',
    inputs: [
      { name: 'name', type: 'string', label: 'name', defaultValue: 'myFunction' },
      { name: 'params', type: 'string', label: 'parameters', defaultValue: 'a, b' },
    ],
    canHaveNext: true, hasBranch: false, branchCount: 0,
    tooltip: 'Define a function with parameters',
    luaGenerator: (block, ctx) => {
      const name = ctx.generateInput(block.inputValues.name, ctx);
      const params = ctx.generateInput(block.inputValues.params, ctx);
      return `${ctx.getIndent()}local function ${name.replace(/"/g, '')}(${params.replace(/"/g, '')})`;
    },
  },
  {
    id: 'func_call',
    category: 'functions', type: 'statement',
    label: 'call %1',
    inputs: [{ name: 'name', type: 'string', label: 'function name', defaultValue: 'myFunction' }],
    canHaveNext: true, hasBranch: false, branchCount: 0,
    luaGenerator: (block, ctx) => {
      const name = ctx.generateInput(block.inputValues.name, ctx);
      return `${ctx.getIndent()}${name.replace(/"/g, '')}()`;
    },
  },
  {
    id: 'func_call_args',
    category: 'functions', type: 'statement',
    label: 'call %1 with %2',
    inputs: [
      { name: 'name', type: 'string', label: 'function name', defaultValue: 'myFunction' },
      { name: 'args', type: 'string', label: 'arguments', defaultValue: '' },
    ],
    canHaveNext: true, hasBranch: false, branchCount: 0,
    luaGenerator: (block, ctx) => {
      const name = ctx.generateInput(block.inputValues.name, ctx);
      const args = ctx.generateInput(block.inputValues.args, ctx);
      return `${ctx.getIndent()}${name.replace(/"/g, '')}(${args.replace(/"/g, '')})`;
    },
  },
  {
    id: 'func_call_return',
    category: 'functions', type: 'expression',
    label: 'call %1 and get result',
    inputs: [{ name: 'name', type: 'string', label: 'function name', defaultValue: 'myFunction' }],
    canHaveNext: false, hasBranch: false, branchCount: 0,
    luaGenerator: (block, ctx) => {
      const name = ctx.generateInput(block.inputValues.name, ctx);
      return `${name.replace(/"/g, '')}()`;
    },
  },
  {
    id: 'func_return',
    category: 'functions', type: 'cap',
    label: 'return %1',
    inputs: [{ name: 'value', type: 'any', label: 'value', defaultValue: '' }],
    canHaveNext: false, hasBranch: false, branchCount: 0,
    luaGenerator: (block, ctx) => `${ctx.getIndent()}return ${ctx.generateInput(block.inputValues.value, ctx)}`,
  },
];
