import { escapeLuaString, sanitize } from '@/utils/luaHelpers';
import { CCProject } from '@/models/Project';
import { generateUICode, parseEventCode } from './uiCodeGen';
import { ExportModes } from '.';

const TEMPLATE_DATA = import.meta.glob("./template/**/*.lua", {
  eager: true, import: "default",
  query: "?raw"
});

export const COMPONENTS_LIST = Object.keys(TEMPLATE_DATA).filter(t => t.includes('/components/')).map(t => t.replace(/\.lua/g, "").replace("./template/", "").split("/").pop()!);

export function generateHeader(projectName: string, author: string): string {
  const lines = [
    '-- ============================================================',
    `-- ${projectName}`,
  ];
  if (author) lines.push(`-- Author: ${author}`);
  lines.push(`-- Generated by CCraft Studio`);
  lines.push(`-- Date: ${new Date().toISOString().split('T')[0]}`);
  lines.push('-- ============================================================');
  lines.push('');
  lines.push('');
  return lines.join('\n');
}

export function getComponentLua(projectName: string, author: string, componentName: string): string {
  return `${generateHeader(projectName, author)}${TEMPLATE_DATA['./template/components/' + componentName + '.lua']}`;
}

export function generateFunctionsFile(projectName: string, author: string, mode: ExportModes): string {
  const getScreenObjectFunction = `
  local mainScreen = {
      events = {
        -- Main Events
        onUpdate = function() end,
        onceLoaded = nil,
        onceLoadedRunned = false,
        -- Other Events
        onKeyPress = {},
        onTimer = {},
        onRedstone = function() end,
        onModemMessage = {}
      }
    };
  function getScreen(name)
    return mainScreen;
  end
  `;
  if (mode === 'codeOnly') {
    return `${generateHeader(projectName, author)}${TEMPLATE_DATA["./template/utils/functions.lua"]}\n${getScreenObjectFunction}`;
  } else {
    return `${generateHeader(projectName, author)}${TEMPLATE_DATA["./template/utils/functions.lua"]}\n\n${TEMPLATE_DATA["./template/utils/ui_functions.lua"]}`;
  }
}

export function generateVarsFile(project: CCProject): string {
  const workingScreens = project.screens.filter(s => s.isWorkingScreen);
  let lines = `${generateHeader(project.name, project.author)}${TEMPLATE_DATA["./template/utils/vars.lua"]}`.split('\n');

  for (const v of project.variables) {
    const safeName = sanitize(v.name);
    switch (v.type) {
      case 'string': lines.push(`${safeName} = "${escapeLuaString(v.defaultValue)}"`); break;
      case 'number': lines.push(`${safeName} = ${parseFloat(v.defaultValue) || 0}`); break;
      case 'boolean': lines.push(`${safeName} = ${v.defaultValue === 'true' ? 'true' : 'false'}`); break;
      case 'table': lines.push(`${safeName} = {}`); break;
    }
  }

  lines.push('');
  lines.push(`workingScreens = { "${workingScreens.map(scn => sanitize(scn.name)).join('", "')}" }`);

  return lines.join('\n');
}

export function generateScreenFile(project: CCProject, screenName: string, uiElements: any[]): string {
  const lines: string[] = [
    '-- =============================================',
    `-- Screen UI: ${screenName}`,
    '-- =============================================',
  ];
  lines.push('');
  lines.push(generateUICode(project, uiElements, screenName, project.displayWidth, project.displayHeight));
  return generateHeader(project.name, project.author) + lines.join('\n');
}

export function generateLogicFile(project: CCProject, screenName: string, blockCode: string): string {
  const lines: string[] = [
    '-- =============================================',
    `-- Screen Logic: ${screenName}`,
    '-- =============================================',
  ];
  lines.push('');
  lines.push(`local screen = getScreen("${sanitize(screenName)}")`);
  lines.push('');
  lines.push(parseEventCode(blockCode, sanitize(screenName)));
  return generateHeader(project.name, project.author) + lines.join('\n');
}

export function generateStartupFile(project: CCProject, mode: ExportModes = 'full'): string {
  const workingScreens = project.screens.filter(s => s.isWorkingScreen);
  const safeName = sanitize(workingScreens[0]?.name ?? 'Screen 1');

  let lines = `${generateHeader(project.name, project.author)}${TEMPLATE_DATA["./template/startup.lua"]}`;
  lines = lines.replace("-- {PROJECT_START}",
    mode === 'uiOnly'
      ? `drawScreens()`
      : (mode === 'codeOnly' ? (`\n` + TEMPLATE_DATA["./template/co_loop.lua"]) : (`\n` + TEMPLATE_DATA["./template/loop.lua"]))
  );

  return lines;
}